version: "3.8"
   
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: userdjango
      MYSQL_PASSWORD: passworddjango
      MYSQL_DATABASE: django
      MYSQL_ROOT: root
      MYSQL_ROOT_PASSWORD: iamroot
    restart:
      unless-stopped
    volumes:
      - ./db_data:/var/lib/mysql
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql:ro
    ports:
      - "3306:3306"
  web:
    build: .
    command: uwsgi --socket :8000 --wsgi-file manage.py
    volumes:
      - .:/code
    ports:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - web